name: VM Tests
on: [push]

jobs:
  test:
    name: AmigaSmalltalkTests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Get AXRT
        run: sudo dpkg -i ./vendor/libaxrt-2.0_40.0-1_amd64.deb
      - name: Get AXRT-dev
        run: sudo dpkg -i ./vendor/libaxrt-2.0-dev_40.0-1_amd64.deb
      - name: Use patched runtime (temporary until new release)
        run: sudo cp ./vendor/libaxrt.so.40.1.20200526 /usr/lib/x86_64-linux-gnu/libaxrt.so
      - name: Make sure prefs are readable
        run: sudo chmod -R a+r /usr/lib/x86_64-linux-gnu/axrt
      - name: set up a tmate session
        uses: mxschmitt/action-tmate@v2
      - name: Build and run tests
        run: make check
