name: VM Tests
on: [push]

jobs:
  test:
    name: AmigaSmalltalkTests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Build and run tests
        run: DISPLAY=:0 make check
